name: Hisa-ECM
version: '${version}'
main: tlz.hisamc.hisaecm.HisaECM
api-version: 1.20
folia-supported: true
depend: [PlaceholderAPI]
authors: [tlzytb]
commands:
  hisaecm:
    description: Main command
  bounty:
    description: Open Bounty GUI
    aliases: [bounties]
permissions:
  hisaecm.admin:
    description: Allows reloading the plugin
    default: op